### ISSUE TITLE
请问如何在 docker-compose.yaml 中添加登录用的用户名和密码

### ISSUE THREAD

**Issue by DerivativeMarmot** [Bililive/BililiveRecorder#365]
格式应该怎么写

**Comment by DerivativeMarmot** [comment]
初始的用户名和密码应该在哪添加

**Comment by DerivativeMarmot** [comment]
可以放一份 docker-compose.yaml 模板到 dockerhub 吗

**Comment by Genteure** [comment]
```yml
version: '3'
services:
    rec:
        image: bililive/recorder
        command: run --bind "http://*:2356" --http-basic-user "用户名" --http-basic-pass "密码" /rec
        volumes:
            - '宿主机路径:/rec'
        ports:
            - '2356:2356'
```

还没测试。
晚点放到网站文档上。
