### ISSUE TITLE
配置文件和视频输出文件放在同一目录，对于k8s不是很友好

### ISSUE THREAD

**Issue by ttp2016** [Bililive/BililiveRecorder#388]
在k8s里挂载视频输出目录后
再使用configmap+subPath挂载配置文件到视频输出目录
由于k8s的configmap在使用了subPath后无法根据新configmap更新配置文件，导致每次更新configmap后需要其他方法来更新配置文件
大佬能否新增一个参数， 可以指定配置文件的位置

**Comment by Genteure** [comment]
可以加个参数。

我对 k8s 不太熟悉，可以简单说下你的用法吗？具体指 “每次更新configmap后需要其他方法来更新配置文件” 这句话。
我的理解是，相当于是修改/替换了 `/rec/config.json` 这个文件？但是直接替换了这个文件也不会热重载啊？

**Comment by ttp2016** [comment]
首先感谢大佬的回复，祝项目越来越好

“每次更新configmap后需要其他方法来更新配置文件”就是指修改/替换了 /rec/config.json 这个文件；

热重载的问题：在k8s里面每次更新配置文件后会根据策略重新生成pod(k8s的pod类似于docker的容器)

k8s配置：
1.  先使用nefs挂载/rec目录；nfs服务提供的大容量存储
2.  使用configMap组件来储存config.json配置，并挂载给/rec/config.json；一般我们更新完k8s配置文件中confgMap定义的config.json后，只需要再执行一下k8s的更新配置命令，就可以重新生成新的pod，就使用新的config.json文件了

问题：

1. 跟/rec目录挂载了nfs来提供存储服务后，再挂载/rec/config.json在k8s里面只能使用subPath来指定挂载进/rec/config.json；如果不使用subPath将config.json挂载进/rec，则使用nfs挂载的/rec就会被/rec/config.json挂载重置，相当于无法提供大容量的存储
2.  k8s使用configMap并添加subPath挂载config.json配置文件后，无法感知configMap的变化，则无法动态修改config.json配置，这是组件定义的，参考官网：https://kubernetes.io/zh-cn/docs/concepts/storage/volumes/#configmap

期望：
能添加一个参数可以指定配置文件的路径，这样在使用configMap挂载config.json时可以挂载给其他的目录如/bilirec/config.json，避免subPath带来的坑

另外设置默认配置路径为/rec/config.json，应该不会有兼容性的问题



k8s配置大概如下

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bilirec
  namespace: bilirec
data:
  config.json: |-
    {
        "version": 2,
        "global": {},
        "rooms": [
            {
                "RoomId": {
                    "HasValue": true,
                    "Value": xxxx
                }
            }
        ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bilirec
  namespace: bilirec
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bilirec
  template:
    metadata:
      labels:
        name: bilirec
    spec:
      volumes:
        - name: media
          nfs:
            path: /media
            server: 192.168.0.1
        - name: bilirec-config
          configMap:
            name: bilirec
      containers:
        - name: bilirec
          image: bililive/recorder
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /rec
              name: media
            - mountPath: /rec/config.json
              name: bilirec-config
              subPath: config.json
```
